name: generate-stack
on: [push]
jobs:
  generate-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install js-yaml
      - run: node .github/workflows/generate-stack/generator.js
      - name: Update the file
        uses: EndBug/add-and-commit@v7 
        with:
          author_name: Adeo Stack Generator
          author_email: noreply@adeo.com
          message: 'Generated stack file for Adeo'
