name: generate-stack
on: [push]
jobs:
  generate-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install js-yaml
      - run: node .github/workflows/generate-stack/generator.js
